version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Strong@Independent1Password
      MYSQL_DATABASE: bd_cabinetmedicale
      MYSQL_USER: root
      MYSQL_PASSWORD: Strong@Independent1Password
    ports:
      - "3306:3306"

  tomcat:
    image: tomcat:8.5-jdk11
    container_name: tomcat_server
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./target/Cabinet_Medical-0.0.1-SNAPSHOT:/usr/local/tomcat/webapps/Cabinet_Medical-0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
